# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f23a0d463a0f5f2e5ee113b9e85684e9f1e27425355a1baca8a3b3e8bdb2bad798bc41de9b54f1549fc477044469388c468166e2cc1a72cd24d88e1ef359ecb

test:
  secret_key_base: 0d234b39d31e26c200580e7b69dbf9a6a6a7aef515265a610315846f93a75d8f3d73e0ce5aa4fb407d117dc0d7e1fff87fc55d2e62c1a6f8d2cc51d2ead47152

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
